version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.5.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: nakfl/cms-live-tutor
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no -v $DEPLOYED_USER@$DEPLOYED_SERVER 'cd repositories/cms-live-tutor && ./deploy.sh'

workflows:
  pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - deploy
      - deploy:
          requires:
            - build-and-push
